name: html_unescape
description: >
  A small library for un-escaping HTML. Supports all Named Character References,
  Decimal Character References and Hexadecimal Character References.
version: 2.0.0-nullsafety.0
homepage: https://github.com/filiph/html_unescape

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dev_dependencies:
  meta: ^1.3.0-nullsafety.6
  test: ^1.16.0-nullsafety.16
  path: ^1.8.0-nullsafety.3
  pedantic: ^1.10.0-nullsafety.3
