name: html_unescape
description: >
  A small library for un-escaping HTML. Supports all Named Character References,
  Decimal Character References and Hexadecimal Character References.
version: 2.0.0
homepage: https://github.com/filiph/html_unescape

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  meta: ^1.3.0
  path: ^1.8.0
  pedantic: ^1.11.0
  test: ^1.16.8
